### ISSUE TITLE
ValueError: Invalid scheme component: https

### ISSUE THREAD

**Issue by grayguest** [romis2012/aiohttp-socks#25]
how to support https proxy, thank you

**Comment by romis2012** [comment]
It depends on what you mean by "https proxy"...

1. We support HTTP proxies that can connect to the target host via SSL/TLS (using CONNECT METHOD). Just use `http` scheme.
2. We don't support proxies that themselves require a secure connection because asyncio doesn't support "TLS in TLS" connections. See https://bugs.python.org/issue37179

**Comment by grayguest** [comment]
ok, thanks to your reply.
